name: Build Android (No Impeller)

on:
  workflow_dispatch: # 这行代码就是召唤“手动运行按钮”的魔法

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'
          cache: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Android NDK & Rust Targets
        run: |
          rustup target add aarch64-linux-android
          cargo install cargo-ndk
          sudo apt-get update && sudo apt-get install -y cmake

      - name: Setup Android NDK Environment
        uses: android-actions/setup-android@v3
        with:
          packages: 'ndk;25.2.9519653'

      - name: Generate Dummy Keystore (解决小白没有原作者签名的报错问题)
        run: |
          keytool -genkey -v -keystore android/app/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -dname "CN=fluxdo, OU=fluxdo, O=fluxdo, L=Unknown, ST=Unknown, C=Unknown" -storepass 123456 -keypass 123456
          echo "storePassword=123456" > android/key.properties
          echo "keyPassword=123456" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Compile APK
        run: |
          dart tool/flutterw.dart build apk --release --target-platform android-arm64 --dart-define=cronetHttpNoPlay=true
          mkdir -p dist
          mv build/app/outputs/flutter-apk/app-release.apk dist/fluxdo-arm64-no-impeller.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fluxdo-android-apk
          path: ./dist
          overwrite: true
